AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  EDMS Serverless Infrastructure (V1 - DynamoDB)
  Bảo mật với Least Privilege IAM Role và AWS SAM.

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024
    Runtime: java21
    Architectures:
      - x86_64
    SnapStart:
      ApplyOn: PublishedVersions
    Environment:
      Variables:
        BUCKET_NAME: !Ref DocumentStorageBucket

Resources:


    # LƯU TRỮ: S3 BUCKET
    DocumentStorageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Sub "edms-docs-${AWS::AccountId}-${AWS::Region}"
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
        VersioningConfiguration:
          Status: Enabled
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: ['*']
              AllowedMethods: ['GET', 'PUT', 'POST']
              AllowedOrigins: ['*']
              MaxAge: 3000

    # COMPUTE: LAMBDA FUNCTION VÍ DỤ
    DocumentCrudFunction:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: backend/
        Handler: com.edms.functions.documentcrud.App::handleRequest
        AutoPublishAlias: live
        Policies:
          - DynamoDBCrudPolicy:
              TableName: !Ref EdmsMainTable
        Events:
          CreateDoc:
            Type: Api
            Properties:
              Path: /documents
              Method: post
          GetDoc:
            Type: Api
            Properties:
              Path: /documents/{id}
              Method: get

  Outputs:
    ApiGatewayEndpoint:
      Description: "URL gốc của hệ thống API"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
    S3BucketName:
      Description: "Tên Bucket chứa tài liệu"
      Value: !Ref DocumentStorageBucket
    TableName:
      Description: "Tên bảng DynamoDB"
      Value: !Ref EdmsMainTable